CREATE TABLE [dbo].[CcbLicenses]
(
	[APPLICATION_ID]		INT				IDENTITY(1, 1) NOT NULL,
	[REGISTRATION_NUMBER]	INT				NOT NULL,
	[NAME]					VARCHAR(MAX)	NOT NULL,
	[SSN]					VARCHAR(MAX)	NOT NULL,
	CONSTRAINT [PK_CcbLicenses] PRIMARY KEY CLUSTERED ([APPLICATION_ID]),
	CONSTRAINT [UC_CcbNumber] UNIQUE ([REGISTRATION_NUMBER])
);
GO