CREATE TABLE [dbo].[Entities]
(
	[ID]			INT				IDENTITY (1, 1) NOT NULL,
	[FIRST_NAME]	VARCHAR(MAX)	NOT NULL,
	[MIDDLE_NAME]	VARCHAR(MAX)	NULL,
	[LAST_NAME]		VARCHAR(MAX)	NOT NULL,
	[ADDRESS]		VARCHAR(MAX)	NOT NULL,
	[CITY]			VARCHAR(MAX)	NOT NULL,
	[STATE]			VARCHAR(MAX)	NOT NULL,
	[ZIP_CODE]		VARCHAR(MAX)	NOT NULL,
	CONSTRAINT [PK_Entities] PRIMARY KEY CLUSTERED ([ID])
)
