CREATE TABLE [dbo].[EntityLicenses]
(
	[USER_ID]				INT		IDENTITY (1, 1) NOT NULL,
	[REGISTRATION_NUMBER]	INT		NOT NULL,
	CONSTRAINT [PK_EntityLicenses] PRIMARY KEY CLUSTERED ([USER_ID], [REGISTRATION_NUMBER]),
	CONSTRAINT [FK_EntityLicenses_Entities] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[Entities] ([ID])
)
